spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    jndi-name:
    username: not_relevant@gmail.com
    password: wagwmwrdidwufylc
    port: 25
    properties:
      mail:
        debug: false
        smtp:
          debug: false
          auth: true
          starttls.enable: true
    protocol: smtp
    test-connection: false